[project]
name = "06-gui-web"
version = "0.1.0"
description = "Simple Web app Exercice, with NiceGUI"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.6",
    "nicegui[native]>=3.0.3",
    "pandas>=2.3.3",
    "plotly>=6.3.1",
]
